### ISSUE TITLE
PolyChord sampling support

### ISSUE THREAD

**Issue by yebai** [TuringLang/NestedSamplers.jl#30]
PolyChord is a Bayesian inference tool for the simultaneous calculation of evidence and sampling of posterior distributions. It is a variation on John Skilling's Nested Sampling, utilising Slice Sampling to generate new live points. 

It would be interesting to investigate support for the PolyChord sampling algorithm, either via Julia's excellent Fortran call interface, or rewrite the algorithm in pure Julia. 

**Python interface for Fortran backend**: https://github.com/PolyChord/PolyChordLite

References:

1.  Handley, W. J., Hobson, M. P., & Lasenby, A. N. (2015). **polychord: nested sampling for cosmology**. Monthy Notices of the Royal Astronomical Society Letters, 450(1), L61–L65.

2. Feroz, F., Hobson, M. P., Cameron, E., & Pettitt, A. N. (2019). **Importance Nested Sampling and the MultiNest Algorithm**. The Open Journal of Astrophysics, 2, 10.

**Comment by mileslucas** [comment]
Following the 0.2 release, this can now be approached by creating a new `Proposals.AbstractProposal`: `Proposals.RandSlice` (mimicking dynesty's `rslice` mode).

**Comment by mileslucas** [comment]
Traditional Polychord method mostly enabled with the merge of #44.

**Comment by yebai** [comment]
> Traditional Polychord method mostly enabled with the merge of #44.

Anything missing for state-of-the-art Polychord (apart from distributed implementation)? Is it the k-means clustering algorithm for live points?

**Comment by mileslucas** [comment]
Nope k means is present in the multi ellipsoidal code. I just don't want to brand anything as being "the polychord algorithm" when there might be minor implementation differences.

**Comment by yebai** [comment]
That makes sense!
