### ISSUE TITLE
What does NestedSamplers output

### ISSUE THREAD

**Issue by ptiede** [TuringLang/NestedSamplers.jl#58]
Hi, I just pulled the newest version of NestedSamplers and am a little confused at the output. 

I ran the example in the docs, and it doesn't look like the return chain is the set of dead points, and weights but rather a resampled version of the chain? Is that right?

**Comment by mileslucas** [comment]
Can you please provide an example of code and point out where your confusion stems from?

In the examples
```
chain, state = sample(model, spl; dlogz=0.2, param_names=["x", "y"])
# optionally resample the chain using the weights
chain_res = sample(chain, Weights(vec(chain["weights"])), length(chain));
```
`chain` has the raw samples and weights. `chain_res` includes an equal number of samples resamples using their statistical weights. `state` has the current state of the sampler, including the live points and `logz` estimate.

**Comment by ptiede** [comment]
Sorry for the bad initial issue! Here is a simple example

```julia
using Distributions
using LinearAlgebra
using NestedSamplers
using StatsFuns: logaddexp

# Gaussian mixture model
σ = 1.0
μ = ones(2)
inv_σ = diagm(0 => fill(1 / σ^2, 2))

function logl(x)
    -sum(abs2, (x.-μ).*inv_σ) - length(x)/2*log(2π*σ)
end
priors = [
    Uniform(-5, 5),
    Uniform(-5, 5)
]
# create the model
# or model = NestedModel(logl, prior_transform)
model = NestedModel(logl, priors);

spl = Nested(2, 1000)

chain,stats = sample(model, spl; dlogz=0.2, param_names=["x","y"])

scatter(chain["x"])
```
This produces the following plot for the chain of x
![gfoo](https://user-images.githubusercontent.com/5565461/115961071-cd5e3700-a4e2-11eb-84a1-15920b108c28.png)

This looks like a resampled version not what I would expect from a nested sampling algorithm that should contract to higher and higher iso-likelihood contours. 

As an aside, I also noticed that the effective sample size 
ESS = 1/sum(w^2),
(which I think is fine since it looks like the reported weights are normalized)
is a lot lower than when I do an equivalent problem with something like dynesty.

**Comment by mileslucas** [comment]
Thanks for the example- it looks like I've introduced a bug in version `0.6`. I was able to reproduce what you've shown here, and compared to what `dynesty` produces. 

I would recommend reverting to version `0.5`, which does appropriately sample while I look further into this


## 0.5
![Screen Shot 2021-04-24 at 6 03 51 PM](https://user-images.githubusercontent.com/14099459/115975088-6dd64a80-a527-11eb-8ba8-accba58082f7.png)

**Comment by mileslucas** [comment]
Okay I found the bug- thankfully it was relatively trivial. Expect a PR soon :)

**Comment by ptiede** [comment]
Awesome! Thanks for the package by the way! It is great to see all the different Julia sampling packages.
