### ISSUE TITLE
New release for Distributions v0.25 compatibility?

### ISSUE THREAD

**Issue by oschulz** [TuringLang/NestedSamplers.jl#63]
Would you consider tagging a new release? NestedSamplers#master is Distributions v0.25 compatible, but the last release isn't.

**Comment by mileslucas** [comment]
https://github.com/TuringLang/NestedSamplers.jl/commit/c5aa3e947ff74feddf2ac6a94b9243a008422223

**Comment by oschulz** [comment]
Merci, @mileslucas !
