### ISSUE TITLE
Confusing kwarg in `Nested`

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/NestedSamplers.jl#74]
![image](https://user-images.githubusercontent.com/71727937/146044357-4b40c221-2dd9-4c2a-889b-e64831a6cabe.png)
Is this the maximum or minimum?

**Comment by mileslucas** [comment]
Ah, it should read minimum. It could use a better description, too. Something like,

"Minimum efficiency (samples accepted / samples generated) before fitting the first bounding volume. This is to allow some burn-in of the sampler and avoid spuriously shrinking the bounds, which can decrease evidence estimate accuracy."

**Comment by ParadaCarleton** [comment]
> Ah, it should read minimum. It could use a better description, too. Something like,
> 
> "Minimum efficiency (samples accepted / samples generated) before fitting the first bounding volume. This is to allow some burn-in of the sampler and avoid spuriously shrinking the bounds, which can decrease evidence estimate accuracy."

Would you endorse these docstrings?
```
- `min_ncall`: The minimum number of iterations before fitting the first bound; used to 
avoid shrinking the bounds before burn-in is completed.
- `min_eff`: Minimum efficiency `(samples accepted / samples generated)` before fitting the 
first bound; used to avoid shrinking the bounds before burn-in is completed.
```

**Comment by mileslucas** [comment]
Yes those look great- feel free to PR!
